site_name: Документация сервиса сотрудников

repo_url: 'https://github.com/yulia633/yulia633.github.io'

theme:
  name: material
  language: ru
  palette:
    primary: white

nav:
  - index.md
  - Главная:
      - mkdocs/index.md
      - mkdocs/main.md
  - Документация:
      - mkdocs/employee/all.md
      - mkdocs/employee/get-person.md
      - mkdocs/employee/create-person.md
