site_name: Документация сервиса сотрудников

repo_url: 'https://github.com/yulia633/yulia633.github.io'

theme:
  name: material
  language: ru
  palette:
    primary: white

nav:
  - Главная:
      - docs/mkdocs/index.md
      - docs/mkdocs/main.md
  - Документация:
      - docs/mkdocs/employee/all.md
      - docs/mkdocs/employee/get-person.md
      - mkdocs/employee/create-person.md



