site_name: Документация сервиса сотрудников

repo_url: 'https://github.com/yulia633/yulia633.github.io'

theme:
  name: material
  language: ru
  palette:
    primary: white
  features:
    - content.code.copy
    - navigation.top
    - navigation.tracking
    - navigation.sections
    - navigation.tabs
    - navigation.expand

extra_css:
  - assets/css/style.css

extra:
  generator: false

exclude_docs: |
  *.drawio

nav:
  - Главная:
      - index.md
      - main.md
  - Документация:
      - employee/all.md
      - employee/get-person.md
      - employee/create-person.md



